### ISSUE TITLE
Fix padding of mirror certificate

### ISSUE THREAD

**Issue by ajaysimha** [sonofspike/cluster_mgnt_roles#31]
Symptom: While running playbook you may encounter this error:

TASK [create_cluster : Load patch for install config] ************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:     ^
fatal: [bastion]: FAILED! => {"changed": false}

Workaround: Add 4 columns of space to the mirror_certificate.txt file

**Comment by dylwong** [comment]
Fixed in feature/skopeo-validate branch
