### ISSUE TITLE
boot_iso DELL Eject Virtual Media (if any) is ignoring errors and not catching failure

### ISSUE THREAD

**Issue by ajaysimha** [sonofspike/cluster_mgnt_roles#42]
TASK [boot_iso : Set Dell OneTimeBoot VirtualCD] *****************************************************************************
ok: [worker1 -> None]

TASK [boot_iso : DELL Eject Virtual Media (if any)] **************************************************************************
ok: [worker1 -> None]

TASK [boot_iso : DELL Insert Virtual Media] **********************************************************************************
fatal: [worker1 -> None]: FAILED! => {"changed": false, "msg": "Unable to find an available VirtualMedia resource supporting ['CD', 'DVD']"}

This is happening because:
- name: DELL Eject Virtual Media (if any)
      community.general.redfish_command:
        category: Manager
        command: VirtualMediaEject
        baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
        username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
        password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
        virtual_media:
          image_url: "{{ boot_iso_url }}"
        resource_id: iDRAC.Embedded.1
      ignore_errors: yes <===

We need to catch and handle this error.

**Comment by arjuhe** [comment]
Check which version of the firmware you are using. Rolling back to version 4.20.20.20 worked for us. Take a look at https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html 
```
Currently, Redfish is only supported on Dell with iDRAC firmware versions 4.20.20.20 through 04.40.00.00 for installer-provisioned installations on bare metal deployments. There is a known issue with version 04.40.00.00.
```

**Comment by ajaysimha** [comment]
Hi Arnaldo,

I see this error especially the 2nd and 3rd all the time:


TASK [boot_iso : DELL Insert Virtual Media]
**********************************************************************************
fatal: [worker2 -> None]: FAILED! => {"changed": false, "msg": "HTTP Error
400 on POST request to '
https://10.1.177.43/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD/Actions/VirtualMedia.InsertMedia',
extended message: 'Unable to mount remote share
http://10.1.196.40:8080/discovery_image_mgmt.iso.'"}

TASK [boot_iso : DELL Insert Virtual Media]
**********************************************************************************
fatal: [worker3 -> None]: FAILED! => {"changed": false, "msg": "Unable to
find an available VirtualMedia resource supporting ['CD', 'DVD']"}

TASK [boot_iso : DELL Insert Virtual Media]
**********************************************************************************
fatal: [worker4 -> None]: FAILED! => {"changed": false, "msg": "Unable to
find an available VirtualMedia resource supporting ['CD', 'DVD']"}

Do you see this issue with rhte 04.20.20.20?

Ajay

**Comment by arjuhe** [comment]
Adding this here to close the thread. As mentioned in our conversation, we've haven't had a boot disk failure since rolling back to 4.20.20. 

Good luck
/Aldo
